name: jetrideruser
description: "A new Flutter project."
publish_to: 'none' 


environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.3
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  dio: ^5.7.0
  flutter_polyline_points: ^2.1.0
  flutter_geofire: ^2.0.4
  firebase_database: ^11.3.1
  fluttertoast: ^8.2.2
  flip_card: ^0.7.0
  brasil_fields: ^1.17.0
  mask_text_input_formatter: ^2.9.0
  credit_card_type_detector: ^3.0.0
  cpf_cnpj_validator: ^2.0.0
  cloud_functions: ^5.5.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - images/


